name: Sonar

on:
  push:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**', '.github/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**', '.github/workflows/**' ]

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  sonar: 
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.CICD_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=traunmus_ci-cd-uebung-traunmueller
          -Dsonar.organization=traunmus
          -Dsonar.branch.name=main
          -Dsonar.java.binaries=target/classes
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


